spring:
  application:
    name: mro-shipping-scv
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/library
    username: kgr
    password: 1234
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    contexts: local
#    enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8088

#jpa:
#  hibernate:
#    ddl-auto: validate
#  show-sql: true
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect

#springdoc:
#  group-configs:
#    - group: library
#      paths-to-match: /api/library/**
